config/routes.rb
Mfm::Application.routes.draw do

  devise_for :users, controllers: {
      confirmations:      'users/confirmations',
      passwords:          'users/passwords',
      registrations:      'users/registrations',
      sessions:           'users/sessions',
      unlocks:            'users/unlocks',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  match '/delayed_job' => DelayedJobWeb, :anchor => false

  match 'admin/index'                 => 'admin#index',              :as => :admin_index
  match 'admin/users'                 => 'admin#users',              :as => :admin_users
  match 'admin/orders'                => 'admin#orders',             :as => :admin_orders
  match 'admin/handle_order/:id'      => 'admin#handle_order',       :as => :admin_handle_order
  match 'admin/handle_ticket/:id'     => 'admin#handle_ticket',      :as => :admin_handle_ticket
  match 'admin/order_modal/:id'       => 'admin#order_modal',        :as => :admin_order_modal
  match 'admin/create_transaction'    => 'admin#create_transaction', :as => :admin_create_transaction
  match 'admin/create_redeem'         => 'admin#create_redeem',      :as => :admin_create_redeem

  match 'home/index'                  => 'home#index',               :as => :home_index
  match 'home/stores'                 => 'home#stores',              :as => :home_stores
  match 'home/delivery'               => 'home#delivery',            :as => :home_delivery
  match 'home/grocery'                => 'home#grocery',             :as => :home_grocery
  match 'home/coupons'                => 'home#coupons',             :as => :home_coupons
  match 'home/plans'                  => 'home#plans',               :as => :home_plans

  match 'home/store_overview/:id'     => 'home#store_overview',      :as => :home_store_overview
  match 'home/store_info/:id'         => 'home#store_info',          :as => :home_store_info
  match 'home/store_good/:id'         => 'home#store_good',          :as => :home_store_good
  match 'home/store_menu/:id'         => 'home#store_menu',          :as => :home_store_menu
  match 'home/store_promo/:id'        => 'home#store_promo',         :as => :home_store_promo
  match 'home/store_review/:id'       => 'home#store_review',        :as => :home_store_review
  match 'home/print_coupon/:id'       => 'home#print_coupon',        :as => :home_print_coupon
  match 'home/dish_modal/:id'         => 'home#dish_modal',          :as => :home_dish_modal

  match 'home/paypal_notify'          => 'home#paypal_notify',       :as => :home_paypal_notify
  match 'home/paypal_cancel'          => 'home#paypal_cancel',       :as => :home_paypal_cancel

  match 'home/phone_start'            => 'home#phone_start',         :as => :home_phone_start
  match 'home/phone_end'              => 'home#phone_end',           :as => :home_phone_end
  match 'home/phone_test'             => 'home#phone_test',          :as => :home_phone_test

  resources :advertisements
  resources :carts do
    member do
      get :type
    end
  end
  resources :cart_items
  resources :orders
  resources :payments
  resources :posts
  resources :roles
  resources :services
  resources :tags
  resources :tickets
  resources :transactions

  resources :stores do
    resources :coupons, :dish_choices, :dish_features, :dish_discounts, :hours, :menus, :plans
  end

  resources :menus do
    resources :categories
  end

  resources :categories do
    resources :dishes
  end

  root :to => 'home#index'

end

app/models/store.rb
class Store < ActiveRecord::Base
  include Hourable

  attr_accessible :delivery_fee, :delivery_minimum, :delivery_radius, :cash_back_rate,
                  :desc, :fax, :name, :phone, :rank, :gallery, :story,
                  :avatar, :avatar_cache, :remove_avatar, # carrierwave and rails_admin
                  :tag_ids, :payment_ids, :service_ids,
                  :address_attributes, :gallery_attributes, :hours_attributes, :menus_attributes

  has_one :address, :as => :addressable
  has_one :gallery, :as => :galleriable

  has_many :coupons, :dependent => :destroy
  has_many :dish_choices, :dependent => :destroy
  has_many :dish_features, :dependent => :destroy
  has_many :dish_discounts, :dependent => :destroy
  has_many :hours, :dependent => :destroy, :as => :hourable
  has_many :menus, :dependent => :destroy, :order => :rank
  has_many :plans, :dependent => :destroy
  has_many :orders

  has_and_belongs_to_many :payments
  has_and_belongs_to_many :services
  has_and_belongs_to_many :tags

  # ========== More ==========

  accepts_nested_attributes_for :address, :allow_destroy => true
  accepts_nested_attributes_for :gallery, :allow_destroy => true
  accepts_nested_attributes_for :hours, :allow_destroy => true
  accepts_nested_attributes_for :menus,  :allow_destroy => true

  mount_uploader :avatar, AvatarUploader

  validates :name, presence: true
  validates :phone, presence: true
  validates :fax, presence: true
  validates :delivery_fee, presence: true
  validates :delivery_minimum, presence: true
  validates :delivery_radius, presence: true

  def has_overview?
    !gallery.nil? && gallery.gallery_photos.size > 0
  end

  def has_effective_coupons?
    coupons.where("rank > 0").size > 0
  end

  def has_good_dishes?
    good_dishes = Dish.joins(:dish_features, :category => :menu).where({ 'menus.store_id' => id, 'dish_features.name' => 'good' })
    good_dishes.size > 0
  end

  # Delivery Types for Carts / Services of Stores
  # ==========================================================
  def has_delivery_service?
    services.include?(Service.find_by_name("delivery_service"))
  end

  def has_melivery_service?
    services.include?(Service.find_by_name("melivery_service"))
  end

  def has_pick_up_service?
    services.include?(Service.find_by_name("pick_up_service"))
  end

  def has_express_service?
    services.include?(Service.find_by_name("express_service"))
  end

  # Generate human and seo friendly url
  # ======================================================
  def to_param
    "#{id} #{name}".parameterize
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  # Authenticate and load @store for the whole controller
  load_and_authorize_resource

  # GET /stores
  # GET /stores.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store.build_address
    @store.build_gallery

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store.build_gallery if @store.gallery.nil?
  end

  # POST /stores
  # POST /stores.json
  def create
    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update_attributes(params[:store])
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= simple_nested_form_for(@store, :html => { :class => 'form-horizontal' }, :validate => true ) do |f| %>
    <%= f.error_notification %>

    <hr/>

    <h4>Basic info:</h4>
    <%= f.input :name %>
    <%= f.input :desc %>
    <%= f.input :rank, :hint => "Decide the order, and 0 means hidden." %>
    <%= f.input :phone, :hint => "Eg. : 9790009988. Don't use - or ()." %>
    <%= f.input :fax, :hint => "Eg. : 9790009988. Don't use - or ()." %>
    <%= f.input :delivery_minimum %>
    <%= f.input :delivery_fee %>
    <%= f.input :delivery_radius %>
    <%= f.input :cash_back_rate %>
    <%= f.association :tags, :as => :check_boxes, :item_wrapper_class => 'inline' %>
    <%= f.association :services, :as => :check_boxes, :item_wrapper_class => 'inline' %>
    <%= f.association :payments, :as => :check_boxes, :item_wrapper_class => 'inline' %>
    <%= f.input :avatar, as: :image_preview, input_html: {preview_version: :small}, :hint => "Use square image (width = height)." %>
    <%= f.input :story, :input_html => {:rows => 5, :cols => 50, :class => 'resizable'} %>

    <hr/>

    <h4>Address:</h4>
    <%= f.fields_for :address do |addr| %>
        <%= addr.input :address1 %>
        <%= addr.input :address2 %>
        <%= addr.input :city %>
        <%= addr.input :state %>
        <%= addr.input :country, :as => :string %>
        <%= addr.input :zip %>
    <% end %>

    <hr/>

    <h4>Gallery:</h4>
    <%= f.fields_for :gallery do |gallery| %>
        <%= gallery.input :name %>
        <%= gallery.input :desc %>
        <hr/>
        <%= gallery.fields_for :gallery_photos do |g| %>
            <%= g.input :name %>
            <%= g.input :desc %>
            <%= g.input :photo, as: :image_preview, input_html: {preview_version: :micro} %>
            <%= g.link_to_remove "Remove", class: 'btn btn-info' %>
        <% end %>
        <%= gallery.link_to_add "Add", :gallery_photos, class: 'btn btn-primary' %>
    <% end %>

    <hr/>

    <h4>Open Hours:</h4>
    <%= f.fields_for :hours do |hour| %>
        <%= hour.input :name, :hint => "Eg. : 0 1 2 3 4 5 6" %>
        <%= hour.input :desc, :hint => "Eg. : Mon - Fri" %>
        <%= hour.input :open_at, :hint => "Eg. : 11:00" %>
        <%= hour.input :close_at, :hint => "Eg. : 21:00" %>
        <%= hour.link_to_remove "Remove", class: 'btn btn-info' %>
    <% end %>
    <%= f.link_to_add "Add", :hours, class: 'btn btn-primary' %>

    <hr/>

    <%= f.button :submit, disable_with: "Saving...", class: 'btn btn-primary' %>
<% end %>

app/views/stores/edit.html.erb
<div class="well">
  <h1>Editing store</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @store %> |
  <%= link_to 'Back', stores_path %>
</div>

app/views/stores/index.html.erb
<div class="well">
  <%= link_to "Manage Payments", payments_path, class: "btn btn-info" %>
  <%= link_to "Manage Services", services_path, class: "btn btn-info" %>
  <%= link_to "Manage Tags", tags_path, class: "btn btn-info" %>
  <%= link_to "Manage Ads", advertisements_path, class: "btn btn-info" %>
  <%= link_to "Manage Posts", posts_path, class: "btn btn-info" %>
  <%= link_to "Manage Users", admin_users_path, class: "btn btn-info" %>
  <%= link_to "Manage Tickets", tickets_path, class: "btn btn-info" %>
  <%= link_to "Manage Orders", admin_orders_path, class: "btn btn-info" %>

  <%= link_to 'New Store', new_store_path, class: "btn btn-primary pull-right" %>

  <br/><br/>

  <h1>Manage Stores</h1>

  <table class='table table-hover table-bordered'>
    <tr>
      <th>Rank</th>
      <th>Name</th>
      <th>Avatar</th>
      <th>Phone/Fax</th>
      <th>Delivery min|fee|radius</th>
      <th>Cash Back Rate</th>
      <th colspan="7">Action</th>
    </tr>

    <% @stores.each do |store| %>
        <tr>
          <td><%= store.rank %></td>
          <td><%= store.name %></td>
          <td><%= image_tag store.avatar_url(:small).to_s if store.avatar? %></td>
          <td><%= store.phone %><br/><%= store.fax %></td>
          <td>
            <%= number_to_currency store.delivery_minimum %> |
            <%= number_to_currency store.delivery_fee %> |
            <%= store.delivery_radius %> miles
          </td>
          <td><%= store.cash_back_rate %></td>
          <td><%= link_to 'Menus', store_menus_path(store) %></td>
          <td><%= link_to 'Featu', store_dish_features_path(store) %></td>
          <td><%= link_to 'Choic', store_dish_choices_path(store) %></td>
          <td><%= link_to 'Disco', store_dish_discounts_path(store) %></td>
          <td><%= link_to 'Coupons', store_coupons_path(store) %></td>
          <!--<td><%= link_to 'Plans', store_plans_path(store) %></td>-->
          <td><%= link_to 'Edit', edit_store_path(store) %></td>
          <td><%= link_to 'X', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </table>
</div>

app/views/stores/new.html.erb
<div class="well">
  <h1>New store</h1>

  <%= render 'form' %>

  <%= link_to 'Back', stores_path %>
</div>

app/views/stores/show.html.erb
<div class="well">
  <p><b>Name:</b><%= @store.name %></p>
  <p><b>Desc:</b><%= @store.desc %></p>
  <p><b>Image:</b><br/><%= image_tag @store.avatar_url.to_s if @store.avatar? %></p>
  <p><b>Phone:</b><%= @store.phone %></p>
  <p><b>Fax:</b><%= @store.fax %></p>
  <p><b>Delivery minimum:</b><%= @store.delivery_minimum %></p>
  <p><b>Delivery fee:</b><%= @store.delivery_fee %></p>
  <p><b>Delivery radius:</b><%= @store.delivery_radius %></p>
  <p><b>Cash Back Rate:</b><%= @store.cash_back_rate %></p>
  <p><b>Position: </b>(<%= @store.address.latitude %>, <%= @store.address.longitude %>)</p>

  <%= link_to 'Edit', edit_store_path(@store) %> |
  <%= link_to 'Back', stores_path %>
</div>