config/routes.rb
Mfm::Application.routes.draw do

  devise_for :users, controllers: {
      confirmations:      'users/confirmations',
      passwords:          'users/passwords',
      registrations:      'users/registrations',
      sessions:           'users/sessions',
      unlocks:            'users/unlocks',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  match '/delayed_job' => DelayedJobWeb, :anchor => false

  match 'admin/index'                 => 'admin#index',              :as => :admin_index
  match 'admin/users'                 => 'admin#users',              :as => :admin_users
  match 'admin/orders'                => 'admin#orders',             :as => :admin_orders
  match 'admin/handle_order/:id'      => 'admin#handle_order',       :as => :admin_handle_order
  match 'admin/handle_ticket/:id'     => 'admin#handle_ticket',      :as => :admin_handle_ticket
  match 'admin/order_modal/:id'       => 'admin#order_modal',        :as => :admin_order_modal
  match 'admin/create_transaction'    => 'admin#create_transaction', :as => :admin_create_transaction
  match 'admin/create_redeem'         => 'admin#create_redeem',      :as => :admin_create_redeem

  match 'home/index'                  => 'home#index',               :as => :home_index
  match 'home/stores'                 => 'home#stores',              :as => :home_stores
  match 'home/delivery'               => 'home#delivery',            :as => :home_delivery
  match 'home/grocery'                => 'home#grocery',             :as => :home_grocery
  match 'home/coupons'                => 'home#coupons',             :as => :home_coupons
  match 'home/plans'                  => 'home#plans',               :as => :home_plans

  match 'home/store_overview/:id'     => 'home#store_overview',      :as => :home_store_overview
  match 'home/store_info/:id'         => 'home#store_info',          :as => :home_store_info
  match 'home/store_good/:id'         => 'home#store_good',          :as => :home_store_good
  match 'home/store_menu/:id'         => 'home#store_menu',          :as => :home_store_menu
  match 'home/store_promo/:id'        => 'home#store_promo',         :as => :home_store_promo
  match 'home/store_review/:id'       => 'home#store_review',        :as => :home_store_review
  match 'home/print_coupon/:id'       => 'home#print_coupon',        :as => :home_print_coupon
  match 'home/dish_modal/:id'         => 'home#dish_modal',          :as => :home_dish_modal

  match 'home/paypal_notify'          => 'home#paypal_notify',       :as => :home_paypal_notify
  match 'home/paypal_cancel'          => 'home#paypal_cancel',       :as => :home_paypal_cancel

  match 'home/phone_start'            => 'home#phone_start',         :as => :home_phone_start
  match 'home/phone_end'              => 'home#phone_end',           :as => :home_phone_end
  match 'home/phone_test'             => 'home#phone_test',          :as => :home_phone_test

  resources :advertisements
  resources :carts do
    member do
      get :type
    end
  end
  resources :cart_items
  resources :orders
  resources :payments
  resources :posts
  resources :roles
  resources :services
  resources :tags
  resources :tickets
  resources :transactions

  resources :stores do
    resources :coupons, :dish_choices, :dish_features, :dish_discounts, :hours, :menus, :plans
  end

  resources :menus do
    resources :categories
  end

  resources :categories do
    resources :dishes
  end

  root :to => 'home#index'

end

app/views/admin/_order_modal.html.erb
<div class="modal hide fade">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">&times;</button>
    <h4>
      <%= @order.cart.delivery_type %>@<%= @order.store.name %>
      <span class="pull-right">
        Pay with <%= @order.payment_type %>(<%= @order.payment_status %>)
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      </span>
    </h4>
  </div>
  <div class="modal-body">
    <table class="table table-bordered">
      <% @order.cart.cart_items.each do |ci| %>
          <tr>
            <td width="200"><%= ci.name %></td>
            <td width="200"><%= ci.note %></td>
            <td width="50"><%= ci.quantity %></td>
            <td width="50"><%= number_to_currency ci.total_price %></td>
          </tr>
      <% end %>
      <tr> <td colspan="4"><b>Note:</b> <%= @order.note %></td>                                                 </tr>
      <tr>
        <td colspan="2" rowspan="4">
          <!--Order User Name-->
          <%= @order.user.firstname + " " + @order.user.lastname %>

          <!--Order User Address-->
          <% if @order.user.address %>
              <br/><%= @order.user.address.address1 %>,&nbsp;<%= @order.user.address.address2 %>
              <br/><%= @order.user.address.city %>,&nbsp;<%= @order.user.address.zip %>
          <% end %>
        </td>
        <td>Subtotal:</td><td><%= number_to_currency @order.cart.subtotal_price %></td>
      </tr>
      <tr> <td>Tax:</td>  <td><%= number_to_currency @order.cart.tax %></td>         </tr>
      <tr> <td>Total:</td><td><%= number_to_currency @order.cart.total_price %></td> </tr>
      <tr> <td>Tip:</td>  <td><%= number_to_currency @order.tip %></td>              </tr>
    </table>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal">Close</button>
  </div>
</div>

app/views/admin/orders.html.erb
<div class="well">
  <div class="pull-right">
    <input type="text" id='datepicker' value="<%= @date.strftime "%F" %>" style="width:90px;margin-top:8px;" />
    <%= link_to "Update", {}, :class => "btn btn-primary", :id => "dateupdater" %>
  </div>
  <h2>Tickets and Orders Summary</h2>
  <br/>

  <h4>Tickets:</h4>
  <table class="table table-hover table-bordered">
    <tr>
      <th>ID</th>
      <th>Status</th>
      <th>Email</th>
      <th>Content</th>
      <th>Action</th>
    </tr>
    <% @tickets.each do |t| %>
        <tr<% unless t.handled %> style="background-color: #ff0000;"<% end %> id="ticket_<%= t.id %>">
          <td><%= t.id %></td>
          <td>Handled</td>
          <td><%= t.email %></td>
          <td><%= t.content %></td>
          <td>
            <%= link_to "Handle", admin_handle_ticket_path(t, handled: true), remote: true, disable_with: "......", class: "btn btn-primary" %>
            <%= link_to "Undo", admin_handle_ticket_path(t, handled: false), remote: true, disable_with: "......", class: "btn btn-primary" %>
          </td>
        </tr>
    <% end %>
  </table>

  <h4>Grocery Orders:</h4>
  <table class='table table-hover table-bordered'>
    <tr>
      <th>ID</th>
      <th>Store</th>
      <th>User</th>
      <th>Payment</th>
      <th>Fee</th>
      <th>Tip</th>
      <th>Order Time</th>
      <th>Note</th>
      <th>Action</th>
    </tr>
    <% @g_orders.each do |order| %>
        <tr<% unless order.handled %> style="background-color: #ff0000;"<% end %> id="order_<%= order.id %>">
          <td><%= order.id %></td>
          <td><%= order.cart.delivery_type %>@<%= order.store.name %></td>
          <td><%= order.user.phone %> / <%= order.user.firstname %> <%= order.user.lastname %></td>
          <td><%= order.payment_type %>(<%= order.payment_status %>)</td>
          <td><%= order.cart.delivery_fee %></td>
          <td><%= order.tip %></td>
          <td><%= order.created_at.strftime("%m/%d/%Y %H:%M%p") %></td>
          <td><%= order.note %></td>
          <td>
            <%= link_to "Details", admin_order_modal_path(order), remote: true, disable_with: "......", class: "btn btn-info" %>
            <%= link_to "Handle", admin_handle_order_path(order, handled: true), remote: true, disable_with: "......", class: "btn btn-primary" %>
            <%= link_to "Undo", admin_handle_order_path(order, handled: false), remote: true, disable_with: "......", class: "btn btn-primary" %>
          </td>
        </tr>
    <% end %>
  </table>

  <h4>Restaurant Orders:</h4>
  <table class='table table-hover table-bordered'>
    <tr>
      <th>ID</th>
      <th>Store</th>
      <th>User</th>
      <th>Payment</th>
      <th>Fee</th>
      <th>Tip</th>
      <th>Order Time</th>
      <th>Note</th>
      <th>Action</th>
    </tr>
    <% @r_orders.each do |order| %>
        <tr<% unless order.handled %> style="background-color: #ff0000;"<% end %> id="order_<%= order.id %>">
          <td><%= order.id %></td>
          <td><%= order.cart.delivery_type %>@<%= order.store.name %></td>
          <td><%= order.user.phone %> / <%= order.user.firstname %> <%= order.user.lastname %></td>
          <td><%= order.payment_type %>(<%= order.payment_status %>)</td>
          <td><%= order.cart.delivery_fee %></td>
          <td><%= order.tip %></td>
          <td><%= order.created_at.strftime("%m/%d/%Y %H:%M%p") %></td>
          <td><%= order.note %></td>
          <td>
            <%= link_to 'Details', admin_order_modal_path(order), remote: true, disable_with: "......", class: "btn btn-info" %>
            <%= link_to ' Handle ', admin_handle_order_path(order, handled: true), remote: true, disable_with: "......", class: "btn btn-primary" %>
            <%= link_to 'Undo', admin_handle_order_path(order, handled: false), remote: true, disable_with: "......", class: "btn btn-primary" %>
          </td>
        </tr>
    <% end %>
  </table>

  <br/>
  <%= link_to 'Back to Stores', stores_path, class: "btn btn-info" %>
</div>

app/views/admin/users.html.erb
<div class="well">
  <h2>Listing Users</h2>
  <table class="table table-bordered">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Address</th>
      <th>Orders</th>
      <th>Confirmed?</th>
      <th>Cash Back</th>
      <th>Actions</th>
    </tr>
    <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.firstname + " " + user.lastname %></td>
          <td><%= user.email %></td>
          <td><%= user.address.address1 + ", " + user.address.address2 if user.address %></td>
          <td>
            <%= user.orders.size %>  (<%= link_to "Details", "javascript:;", class: "orders_toggler", style: "font-size: 12px;" %>)
            <div style="display: none;">
              <% user.orders.each do |order| %>
                  <%= order.id %> |
                  <%= order.payment_type %> |
                  <%= order.payment_status %> |
                  <br/>
              <% end %>
            </div>
          </td>
          <td><%= user.confirmed? %></td>
          <td>
            <span id="cash_back_<%= user.id %>"><%= user.cash_back %></span>
            (<%= link_to "Change", "javascript:;", class: "orders_toggler", style: "font-size: 12px;" %>)
            <div style="display: none;">
              <%= form_tag(admin_create_transaction_path, :method => "post", :remote => true) do %>
                  <h4>Add Amount</h4>
                  <%= text_field_tag "amount", 0, style: "width: 30px;margin-top: 10px;" %>
                  <%= hidden_field_tag "user_id", user.id %>
                  <%= submit_tag "Save", class: "btn btn-primary", :disable_with => "Saving..." %>
              <% end %>
            </div>
          </td>
          <td><%= link_to "Edit User", "#" %></td>
        </tr>
    <% end %>
  </table>

  <br/>
  <%= link_to 'Back to Stores', stores_path, class: "btn btn-info" %>
</div>