config/routes.rb
Mfm::Application.routes.draw do

  devise_for :users, controllers: {
      confirmations:      'users/confirmations',
      passwords:          'users/passwords',
      registrations:      'users/registrations',
      sessions:           'users/sessions',
      unlocks:            'users/unlocks',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  match '/delayed_job' => DelayedJobWeb, :anchor => false

  match 'admin/index'                 => 'admin#index',              :as => :admin_index
  match 'admin/users'                 => 'admin#users',              :as => :admin_users
  match 'admin/orders'                => 'admin#orders',             :as => :admin_orders
  match 'admin/handle_order/:id'      => 'admin#handle_order',       :as => :admin_handle_order
  match 'admin/handle_ticket/:id'     => 'admin#handle_ticket',      :as => :admin_handle_ticket
  match 'admin/order_modal/:id'       => 'admin#order_modal',        :as => :admin_order_modal
  match 'admin/create_transaction'    => 'admin#create_transaction', :as => :admin_create_transaction
  match 'admin/create_redeem'         => 'admin#create_redeem',      :as => :admin_create_redeem

  match 'home/index'                  => 'home#index',               :as => :home_index
  match 'home/stores'                 => 'home#stores',              :as => :home_stores
  match 'home/delivery'               => 'home#delivery',            :as => :home_delivery
  match 'home/grocery'                => 'home#grocery',             :as => :home_grocery
  match 'home/coupons'                => 'home#coupons',             :as => :home_coupons
  match 'home/plans'                  => 'home#plans',               :as => :home_plans

  match 'home/store_overview/:id'     => 'home#store_overview',      :as => :home_store_overview
  match 'home/store_info/:id'         => 'home#store_info',          :as => :home_store_info
  match 'home/store_good/:id'         => 'home#store_good',          :as => :home_store_good
  match 'home/store_menu/:id'         => 'home#store_menu',          :as => :home_store_menu
  match 'home/store_promo/:id'        => 'home#store_promo',         :as => :home_store_promo
  match 'home/store_review/:id'       => 'home#store_review',        :as => :home_store_review
  match 'home/print_coupon/:id'       => 'home#print_coupon',        :as => :home_print_coupon
  match 'home/dish_modal/:id'         => 'home#dish_modal',          :as => :home_dish_modal

  match 'home/paypal_notify'          => 'home#paypal_notify',       :as => :home_paypal_notify
  match 'home/paypal_cancel'          => 'home#paypal_cancel',       :as => :home_paypal_cancel

  match 'home/phone_start'            => 'home#phone_start',         :as => :home_phone_start
  match 'home/phone_end'              => 'home#phone_end',           :as => :home_phone_end
  match 'home/phone_test'             => 'home#phone_test',          :as => :home_phone_test

  resources :advertisements
  resources :carts do
    member do
      get :type
    end
  end
  resources :cart_items
  resources :orders
  resources :payments
  resources :posts
  resources :roles
  resources :services
  resources :tags
  resources :tickets
  resources :transactions

  resources :stores do
    resources :coupons, :dish_choices, :dish_features, :dish_discounts, :hours, :menus, :plans
  end

  resources :menus do
    resources :categories
  end

  resources :categories do
    resources :dishes
  end

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_filter :yelp_client, :only => [:store_review, :store_overview]
  before_filter :new_ticket
  before_filter :store_setup, :only => [:store_overview, :store_good, :store_info, :store_menu, :store_promo, :store_review]

  # Main Pages
  # ======================================================
  def index
    @ads = Advertisement.all
    @posts = Post.all
  end

  def stores
    @tags = Tag.includes(:stores).where("rank > 0").order("rank")
  end

  def delivery
    @stores = Store.includes(:address).where("rank > 0").order("rank")
    @addresses = []
    @stores.each { |store| @addresses << store.address }

    if @addresses
      @json = @addresses.to_gmaps4rails
    end
  end

  def grocery
    @store = Store.find(1)
    @cart = current_cart(@store.id, false)
    @dishes = Dish.joins(:dish_features, :category => :menu)
    .where({ 'menus.store_id' => @store.id, 'dish_features.name' => 'good' }).order("rank") #.select("distinct(dishes.id)")
    @store_still_open = @store.still_open?
    @menu_still_open = true
    @can_order_online = @store.can_order_online?
  end

  def plans
    @plans = Plan.all
  end

  def coupons
    @coupons = Coupon.includes({ :store => :address })
    @addresses = []
    @coupons.each { |coupon| @addresses << coupon.store.address }

    if @addresses
      @json = @addresses.to_gmaps4rails
    end
  end

  # All About Stores
  # ======================================================
  def store_overview
    @gallery = @store.gallery
    @photos = @gallery.gallery_photos if @gallery

    # store_review
    #=========================
    request = Yelp::Phone::Request::Number.new(phone_number: @store.phone, yws_id: APP_CONFIG['yelp_yws_id'])
    response = @client.search(request)
    @reviews = response["businesses"]

    # store_info
    #=========================
    @addresses = []
    @addresses << @store.address
    @json = @addresses.to_gmaps4rails
  end

  def store_info
    @addresses = []
    @addresses << @store.address
    @json = @addresses.to_gmaps4rails
  end

  def store_good
    @dishes = Dish.joins(:dish_features, :category => :menu)
    .where({ 'menus.store_id' => @store.id, 'dish_features.name' => 'good' }).order("rank") #.select("distinct(dishes.id)")
  end

  def store_menu
  end

  def store_promo
  end

  def store_review
    request = Yelp::Phone::Request::Number.new(phone_number: @store.phone, yws_id: APP_CONFIG['yelp_yws_id'])
    response = @client.search(request)
    @reviews = response["businesses"]
  end

  require 'open-uri'

  def print_coupon
    @coupon = Coupon.find(params[:id])

    if mobile_device?
      if Rails.env.production?
        url = @coupon.photo_url.to_s
        data = open(url).read
        send_data data, :filename=>"coupon_#{@coupon.id}.jpg", :type => 'image/jpeg', :disposition => 'attachment'
      else
        send_file Rails.public_path + @coupon.photo_url.to_s, :type => 'image/jpeg', :disposition => 'attachment'
      end
    else
      render :layout => false
    end
  end

  # The Paypal IPN Notify Page
  # ======================================================

  protect_from_forgery :except => [:paypal_notify]

  include ActiveMerchant::Billing::Integrations

  def paypal_notify
    ActiveMerchant::Billing::Base.mode = :test
    notify = Paypal::Notification.new(request.raw_post)
    order = Order.find(notify.invoice)
    if notify.acknowledge
      begin
        amount_in_db = Money.new ((order.cart.total_price+order.tip)*100).round
        if notify.complete? and amount_in_db == notify.amount
          order.payment_status = 'paid'
          order.updated_at = Time.now

          # How to notice the paypal order
          #Order.delay.to_fax(order.id)
          #Order.delay(run_at: 3.minutes.from_now).to_phone(order.id)
          Order.delay.to_phone(order.id)
          # Create cash back for this order
          order.to_transaction
        else
          logger.error("Failed to verify Paypal's notification, please investigate")
        end
      rescue => e
        order.payment_status = 'pending'
        raise
      ensure
        order.save
      end
    end

    render :nothing => true
  end

  def paypal_cancel

  end

  # Twilio Phone Instructions
  # ======================================================
  def phone_start
    @order_id = params[:order_id]
    @post_to = "https://" + APP_CONFIG['domain'] + "/home/phone_end?order_id=#{@order_id}"
    render :action => "phone_start.xml.builder", :layout => false
  end

  def phone_end
    @order_id = params[:order_id]

    if !params['Digits'] || (params['Digits'] != '1' && params['Digits'] != '2')
      redirect_to :action => 'phone_start', :order_id => @order_id
      return
    elsif params['Digits'] == '1'
      @msg = "You pressed one, you got the order."
      @order = Order.find(@order_id)
      @order.status = "fax_succeeded"
      @order.handled = true
      @order.save
    elsif params['Digits'] == '2'
      @msg = "You pressed two, you did not get the order. We'll look at it."
      @order = Order.find(@order_id)
      @order.status = "fax_failed"
      @order.handled = false
      @order.save
    end

    #@redirect_to = "https://" + APP_CONFIG['domain'] + "/home/phone_start?order_id=#{@order_id}"
    render :action => "phone_end.xml.builder", :layout => false
  end

  def phone_test
    Order.to_phone(1)
    render :nothing => true
  end

  # Load the dish choices
  # ======================================================

  def dish_modal
    @dish = Dish.find(params[:id])
    @still_open = @dish.category.menu.store.still_open? && @dish.category.menu.still_open?

    respond_to do |format|
      format.js
      format.mjs
    end
  end

  private
  def yelp_client
    @client = Yelp::Client.new
  end

  def new_ticket
    @ticket = Ticket.new
  end

  def store_setup
    @store = Store.find(params[:id])
    if params[:delivery_type]
      session["cart_delivery_type_#{@store.id}"] = params[:delivery_type]
    else
      unless session["cart_delivery_type_#{@store.id}"]
        if @store.has_delivery_service?
          session["cart_delivery_type_#{@store.id}"] = 'delivery'
        elsif @store.has_melivery_service?
          session["cart_delivery_type_#{@store.id}"] = 'melivery'
        elsif @store.has_pick_up_service?
          session["cart_delivery_type_#{@store.id}"] = 'pick_up'
        elsif @store.has_express_service?
          session["cart_delivery_type_#{@store.id}"] = 'express'
        end
      end
    end
    @cart = current_cart(@store.id, false)
    @has_cart = true  # Show the cart toggle in mobile version
    @store_still_open = @store.still_open?
    @menu_still_open = true
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_order_modal.html.erb
<div class="modal hide fade">
  <div class="modal-header">
    <button class="close" data-dismiss="modal">&times;</button>
    <h4>
      <%= @order.cart.delivery_type %>@<%= @order.store.name %>
      <span class="pull-right">
        Pay with <%= @order.payment_type %>(<%= @order.payment_status %>)
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      </span>
    </h4>
  </div>
  <div class="modal-body">
    <table class="table table-bordered">
      <% @order.cart.cart_items.each do |ci| %>
          <tr>
            <td width="200"><%= ci.name %></td>
            <td width="200"><%= ci.note %></td>
            <td width="50"><%= ci.quantity %></td>
            <td width="50"><%= number_to_currency ci.total_price %></td>
          </tr>
      <% end %>
      <tr> <td colspan="4"><b>Note:</b> <%= @order.note %></td>                                                 </tr>
      <tr>
        <td colspan="2" rowspan="4">
          <!--Order User Name-->
          <%= @order.user.firstname + " " + @order.user.lastname %>

          <!--Order User Address-->
          <% if @order.user.address %>
              <br/><%= @order.user.address.addr1 + " " + @order.user.address.addr2 %>
              <br/><%= @order.user.address.city + " " + @order.user.address.zip %>
          <% end %>
        </td>
        <td>Subtotal:</td><td><%= number_to_currency @order.cart.subtotal_price %></td>
      </tr>
      <tr> <td>Tax:</td>  <td><%= number_to_currency @order.cart.tax %></td>         </tr>
      <tr> <td>Total:</td><td><%= number_to_currency @order.cart.total_price %></td> </tr>
      <tr> <td>Tip:</td>  <td><%= number_to_currency @order.tip %></td>              </tr>
    </table>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal">Close</button>
  </div>
</div>

app/views/home/_store_cart.html.erb
<div class="span4">
  <div class="well" id="side">
    <div id="cart">
      <% if @cart %>
          <%= render @cart %>
      <% elsif !(@store.has_delivery_service? || @store.has_melivery_service? || @store.has_pick_up_service? || @store.has_express_service?) %>
          <%= image_tag "/assets/mfm_logo.png" %>
          <h4><%= @store.name %> cannot order online, please call <span style="color: #8b0000;"><%= @store.phone %></span> to place order.</h4>
      <% else %>
          <%= image_tag "/assets/mfm_logo.png" %>
          <h4>Your Cart Is Empty!</h4>
      <% end %>
    </div>
  </div>
</div>

app/views/home/coupons.html.erb
<div class="row">
  <div class="span7" id="main">
    <div class="well">
      <table class="table table-hover" style="margin-bottom: 0px;">
        <% @coupons.each do |coupon| %>
            <tr>
              <td width="35%">
                <%= link_to_function image_tag(coupon.photo_url(:micro).to_s, alt: 'Meals4.Me', style: "width:200px;height:150px;"),
                                     "$('#modal_wrap_photo .modal').modal('show').find('.modal-body').html(\"<img src=#{coupon.photo_url.to_s} alt='Meals4.Me' />\")" %>
              </td>
              <td width="65%">
                <table style="margin: 0px;">
                  <tr>
                    <td colspan="2" style="border-top: none;padding: 5px;">
                      <h4><%= coupon.name %> @ <%= link_to coupon.store.name, home_store_promo_path(coupon.store) %></h4>
                      <span><%= coupon.desc %></span>
                    </td>
                  </tr>
                  <tr>
                    <td style="border-top: none;padding: 5px;" width="50%">
                      <% if coupon.scope.include? "in_store" %>
                          <b>For dine-in or phone order, print coupon.</b>
                          <%= link_to "Print Coupon", "javascript:;", class: "btn btn-primary", style: "width: 90px;",
                                      onclick: "window.open('/home/print_coupon/#{coupon.id}','PrintCoupon','height=600, width=800, top=150,left=300, toolbar=no, menubar=no, scrollbars=no, resizable=no,location=no, status=no');" %>
                      <% end %>
                    </td>
                    <td style="border-top: none;padding: 5px;" width="50%">
                      <% if coupon.scope.include? "online" %>
                          <b>For online order, click for coupon code.</b>

                          <% if coupon.still_open? %>
                              <%= link_to "Coupon Code", "javascript:;", class: "btn btn-primary cfc", style: "width: 90px;" %>
                              <%= link_to coupon.encode_coupon, "javascript:;", class: "btn btn-info cfc", style: "display: none;width: 90px;" %>
                          <% else %>
                              <%= link_to "Coupon Code", "javascript:alert('Not the right time. Please check the effective time on the coupon.');",
                                          class: "btn btn-primary", style: "width: 90px;" %>
                          <% end %>
                    <% end %>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="span5">
    <div class="well" id="side_map">
      <%= gmaps(
                  :map_options => { :auto_adjust => true },
                  :markers => { :data => @json, :options => { :list_container => "markers_list" }}
          )
      %>
      <ul id="markers_list" style="display: none;"></ul>
    </div>
  </div>
</div>

app/views/home/coupons.mobile.erb
<div data-role="content">
  <br/>
  <ul data-role="listview" data-inset="true" data-filter="true" data-theme="e" data-divider-theme="e">
    <% @coupons.each do |coupon| %>
        <li>
          <%= link_to coupon.photo_url.to_s, rel: 'external', class: "zoom" do %>
              <%= image_tag(coupon.photo_url(:small).to_s, :width => 100, :height => 100) %>
              <h3><%= coupon.name %></h3>
              <p><%= coupon.start_at.strftime("%Y-%m-%d") %> to <%= coupon.end_at.strftime("%Y-%m-%d") %></p>
          <% end %>
        </li>
        <li data-role="list-divider">
          <%= link_to "Save Coupon", home_print_coupon_path(coupon), data: {role: 'button', mini: true}, rel: "external" %>
        </li>
    <% end %>
  </ul>
</div><!-- /content -->

app/views/home/delivery.html.erb
<div class="row">
  <div class="span7" id="main">
    <div class="well">
      <table class="table table-hover" style="margin-bottom: 0px;">
        <% @stores.each do |store| %>
            <tr>
              <td width="30%">
                <%= link_to(image_tag(store.avatar_url.to_s, alt: 'Meals4.Me', style: "width:100px;height:100px;"), home_store_good_path(store)) %>
              </td>
              <td width="50%">
                <div>
                  <h4><%= store.name %>
                    <% if store.cash_back_rate > 0 %>
                        <span style="color: green;font-weight: bold;font-family: times;font-style: italic;">
                          &nbsp;<%= store.cash_back_rate * 100 %>% Reward
                        </span>
                    <% end %>
                  </h4>
                  <p><b>Tags:</b> <% store.tags.each do |t| %><%= t.name %>,&nbsp;<% end %></p>
                  <p><%= store.phone %> | <%= store.address.address1 %></p>
                </div>
              </td>
              <td width="20%">
                <br/>
                <%= link_to 'View Menu', home_store_good_path(store), :class => 'btn btn-primary' %>
              </td>
            </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="span5">
    <div class="well" id="side_map">
      <%= gmaps(
                  :map_options => { :auto_adjust => true },
                  :markers => { :data => @json, :options => { :list_container => "markers_list" }}
          )
      %>
      <ul id="markers_list" style="display: none;"></ul>
    </div>
  </div>
</div><!--/row-->

<!-- Click Button To Load Information With The Store -->
<div class="well" id="load_box_wrap">
  <a class="close" href="javascript:;">x&nbsp;</a>
  <div class="well" id="load_box"></div>
</div>

app/views/home/grocery.html.erb
<div class="well">
  <div class="row-fluid">
    <div class="span3">
      <%= image_tag @store.avatar_url.to_s, :width => '100%' %>
    </div>
    <div class="span6">
      <br/>
      <h1><%= @store.name %></h1>
      <br/>
      <h4>All grocery will be picked up at nearest supermarket (HEB, Kroger, or Walmart) and deliveryed to you directly.</h4>
      <br/>
      <h4>We are coming soon, please return and check later.</h4>
    </div>
  </div>
</div>

<div class="row">
  <div class="span8" id="main">
    <div class="well">
      <div class="row-fluid">
        <ul class="thumbnails">
          <% @dishes.each do |dish| %>
              <% @menu_still_open = dish.category.menu.still_open? %>
              <li class="span4">
                <div class="thumbnail">
                  <%= image_tag dish.photo_url(:small).to_s  %>
                  <div class="caption">
                    <b><%= truncate(dish.name, length: 30) %></b>
                    <% dish.dish_features.each do |df| %>
                        <div style="width: 16px;height: 16px;margin-right: 4px;" class="pull-right icons_dish_features-dish_feature_<%= df.name %>"></div>
                    <% end %>
                    <% if @can_order_online %>
                        <% if @store_still_open && @menu_still_open %>
                            <%= link_to number_to_currency(dish.price), home_dish_modal_path(dish), :remote => true,
                                        :class => 'pre_order btn btn-primary pull-right' %>
                        <% else %>
                            <%= link_to number_to_currency(dish.price), "javascript:alert('" + Dish::ERROR_MSG + "');",
                                        :class => 'btn btn-inverse pull-right' %>
                        <% end %>
                    <% else %>
                        <%= link_to number_to_currency(dish.price), 'javascript:alert("' + @store.name.to_s + ' cannot order online, please call ' + @store.phone + ' to place order!");',
                                    :class => 'btn btn-inverse pull-right' %>
                    <% end %>
                    <i><%= truncate(sanitize(dish.desc), length: 40) %></i>
                  </div>
                </div>
              </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="span4">
    <div class="well" id="side">
      <div id="cart"><%= render @cart %></div>
      <div id="modal_wrap"></div>
    </div>
  </div>
</div><!--/row-->

app/views/home/grocery.mobile.erb
<div data-role="content" data-inset="false">
  <div class="ui-body ui-body-e">
    <h3><%= @store.name %></h3>
    <h3>All grocery will be picked up at nearest supermarket (HEB, Kroger, or Walmart) and deliveryed to you directly.</h3>
    <h3>We are coming soon, please return and check later.</h3>
  </div>

  <ul data-role="listview" data-inset="true">
    <% @store.menus.each do |menu| %>
        <% menu.categories.each do |category| %>
            <% category.dishes.each do |dish| %>
                <li>
                  <%= link_to home_dish_modal_path(dish), :remote => true do %>
                      <%= image_tag dish.photo_url(:small).to_s, :width => 100, :height => 100 %>
                      <h3><%= dish.name %></h3>
                      <p><%= number_to_currency dish.price %></p>
                  <% end %>
                </li>
            <% end %>
        <% end %>
    <% end %>
  </ul>

  <div id="modal_wrap"></div>
</div><!-- /content -->

app/views/home/index.mobile.erb
<div data-role="content">
  <!--<div class="ui-body ui-body-e" style="padding: 10px;;">-->
    <!--<%= image_tag "/assets/mfm_logo.png", :style => 'width:100%;' %>-->
  <!--</div>-->

  <ul data-role="listview" data-inset="true" data-filter="false" id="index_ul">
    <li>
      <%= link_to home_stores_path, :rel => "external" do %>
          <%= image_tag "/assets/restaurant_hub.jpg" %>
          <h3><br/><br/>Restaurant<br/>Hub</h3>
      <% end %>
    </li>
    <li>
      <%= link_to home_delivery_path, :rel => "external" do %>
          <%= image_tag "/assets/restaurant_delivery.jpg" %>
          <h3><br/><br/>Restaurant<br/>Delivery</h3>
      <% end %>
    </li>
    <li>
      <%= link_to home_coupons_path, :rel => "external" do %>
          <%= image_tag "/assets/restaurant_coupons.jpg" %>
          <h3><br/><br/>Restaurant<br/>Coupons</h3>
      <% end %>
    </li>
    <!--<li>-->
      <!--<%= link_to home_grocery_path, :rel => "external" do %>-->
          <!--<%= image_tag "/assets/grocery_delivery.jpg" %>-->
          <!--<h3><br/><br/>Grocery<br/>Delivery</h3>-->
      <!--<% end %>-->
    <!--</li>-->
  </ul>

  <div class="fb-like-box" data-href="https://www.facebook.com/pages/meals4me/149705428516213"
       data-width="400" data-height="540" data-border-color="#FFFFFF" data-show-faces="true" data-stream="true" data-header="false"></div>
</div><!-- /content -->

app/views/home/store_info.html.erb
<%= render 'store_header' %>

<div class="row">
  <div class="span8" id="main">
    <div class="well">

      <%= gmaps(
                  :map_options => { :auto_adjust => true, :auto_zoom => false, :zoom => 16 },
                  :markers => { :data => @json, :options => {}}
          )
      %>

      <h4>Address:</h4>
      <%= @store.address.address1 %>
      <br/>
      <%= @store.address.address2 if @store.address.address2 %>

      <h4>Hours:</h4>
      <ul>
        <% @store.hours.each do |h| %>
            <li><%= h.desc %>: <%= h.open_at %> - <%= h.close_at %></li>
        <% end %>
      </ul>
      <br/>

      <h4>Tags:</h4>
      <% @store.tags.each do |t| %>
          <%= t.name %>
      <% end %>
      <br/><br/>

      <h4>Payments:</h4>
      <% @store.payments.each do |p| %>
          <%= image_tag p.avatar_url(:small).to_s if p.avatar? %>
      <% end %>
      <br/><br/>

      <h4>Delivery Policy:</h4>
      Within 3 miles.
      <br/><br/>

      <p><br/><%= link_to 'View Menu', home_store_menu_path(@store), :class => 'btn btn-primary' %></p>
    </div>
  </div>

  <%= render 'store_cart' %>
</div><!--/row-->

app/views/home/store_menu.html.erb
<%= render 'store_header' %>

<div class="row">
  <div class="span8" id="main">
    <div class="well">
      <div class="row-fluid">
        <ul class="nav nav-tabs first_child_active" style="margin-bottom: 0px;">
          <% @store.menus.each do |menu| %>
              <li><a href="#menu_<%= menu.id %>"><%= menu.name %></a></li>
          <% end %>
        </ul>

        <div class="tab-content first_child_active" style="background-color: #ffffff;border-left: 1px solid #dddddd;padding: 20px;">
          <% @store.menus.each do |menu| %>
              <% @menu_still_open = menu.still_open? %>
              <div class="tab-pane" id="menu_<%= menu.id %>" style="display:block;">
                <% menu.categories.each do |category| %>
                    <section id="<%= category.name %>">
                      <h4><%= category.name %></h4>
                      <ul class="thumbnails">
                        <% category.dishes.each do |dish| %>
                            <li class="span6" style="margin-bottom:10px">
                              <% if session["cart_delivery_type_#{@store.id}"] %>
                                  <% if @store_still_open && @menu_still_open %>
                                      <div class="thumbnail store_menu_dish_wrap_open" rel="popover" title="<%= dish.name %>"
                                           data-content="<%= dish.desc.empty? ? "Info coming soon ..." : sanitize(dish.desc) %>">
                                        <%= link_to home_dish_modal_path(dish), :remote => true do %>
                                            <%= truncate(dish.name, length: 40) %>
                                            <i class="pull-right"><%= number_to_currency(dish.price) %></i>
                                            <% dish.dish_features.each do |df| %>
                                                <div style="width: 16px;height: 16px;margin-right: 4px;" class="pull-right icons_dish_features-dish_feature_<%= df.name %>"></div>
                                            <% end %>
                                        <% end %>
                                      </div>
                                  <% else %>
                                      <div class="thumbnail store_menu_dish_wrap_closed" rel="popover" title="<%= dish.name %>"
                                           data-content="<%= dish.desc.empty? ? "Info coming soon ..." : sanitize(dish.desc) %>">
                                        <%= link_to "javascript:alert('" + Dish::ERROR_MSG + "');" do %>
                                            <%= truncate(dish.name, length: 40) %>
                                            <i class="pull-right"><%= number_to_currency(dish.price) %></i>
                                            <% dish.dish_features.each do |df| %>
                                                <div style="width: 16px;height: 16px;margin-right: 4px;" class="pull-right icons_dish_features-dish_feature_<%= df.name %>"></div>
                                            <% end %>
                                        <% end %>
                                      </div>
                                  <% end %>
                              <% else %>
                                  <div class="thumbnail store_menu_dish_wrap_closed" rel="popover" title="<%= dish.name %>"
                                       data-content="<%= dish.desc.empty? ? "Info coming soon ..." : sanitize(dish.desc) %>">
                                    <%= link_to 'javascript:alert("' + @store.name.to_s + ' cannot order online, please call ' + @store.phone + ' to place order!");' do %>
                                        <%= truncate(dish.name, length: 40) %>
                                        <i class="pull-right"><%= number_to_currency(dish.price) %></i>
                                        <% dish.dish_features.each do |df| %>
                                            <div style="width: 16px;height: 16px;margin-right: 4px;" class="pull-right icons_dish_features-dish_feature_<%= df.name %>"></div>
                                        <% end %>
                                    <% end %>
                                  </div>
                              <% end %>
                            </li>
                        <% end %>
                      </ul>
                    </section>
                <% end %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%= render 'store_cart' %>
</div><!--/row-->

app/views/home/store_menu.mobile.erb
<div data-role="content">
  <%= render 'store_header' %>

  <div data-role="collapsible-set" data-inset="true" data-content-theme="d">
    <% @store.menus.each do |menu| %>
        <% @menu_still_open = menu.still_open? %>
        <% menu.categories.each do |category| %>
            <div data-role="collapsible">
              <h2><%= category.name %></h2>
              <ul data-role="listview" data-split-icon="gear" data-inset="false" data-icon="false" data-filter-theme="c" data-divider-theme="d">
                <% category.dishes.each do |dish| %>
                    <li>
                      <% if session["cart_delivery_type_#{@store.id}"] %>
                          <% if @store_still_open && @menu_still_open %>
                              <%= link_to (number_to_currency dish.price.to_s + " " + dish.name), home_dish_modal_path(dish), remote: true,
                                          style: "font-weight:normal;font-size:14px;padding-right:2px;padding-left:2px;" %>
                          <% else %>
                              <%= link_to (number_to_currency dish.price.to_s + " " + dish.name), "javascript: alert('" + Dish::ERROR_MSG + "');",
                                          style: "font-weight:normal;font-size:14px;padding-right:2px;padding-left:2px;" %>
                          <% end %>
                      <% else %>
                          <%= link_to (number_to_currency dish.price.to_s + " " + dish.name), 'javascript:alert("' + @store.name.to_s + ' cannot order online, please call ' + @store.phone + ' to place order!");',
                                      style: "font-weight:normal;font-size:14px;padding-right:2px;padding-left:2px;" %>
                      <% end %>
                    </li>
                <% end %>
              </ul>
            </div>
        <% end %>
    <% end %>
  </div>

  <div id="modal_wrap"></div>
</div><!-- /content -->