config/routes.rb
Mfm::Application.routes.draw do

  devise_for :users, controllers: {
      confirmations:      'users/confirmations',
      passwords:          'users/passwords',
      registrations:      'users/registrations',
      sessions:           'users/sessions',
      unlocks:            'users/unlocks',
      omniauth_callbacks: 'users/omniauth_callbacks'
  }

  match '/delayed_job' => DelayedJobWeb, :anchor => false

  match 'admin/index'                 => 'admin#index',              :as => :admin_index
  match 'admin/users'                 => 'admin#users',              :as => :admin_users
  match 'admin/orders'                => 'admin#orders',             :as => :admin_orders
  match 'admin/handle_order/:id'      => 'admin#handle_order',       :as => :admin_handle_order
  match 'admin/handle_ticket/:id'     => 'admin#handle_ticket',      :as => :admin_handle_ticket
  match 'admin/order_modal/:id'       => 'admin#order_modal',        :as => :admin_order_modal
  match 'admin/create_transaction'    => 'admin#create_transaction', :as => :admin_create_transaction
  match 'admin/create_redeem'         => 'admin#create_redeem',      :as => :admin_create_redeem

  match 'home/index'                  => 'home#index',               :as => :home_index
  match 'home/stores'                 => 'home#stores',              :as => :home_stores
  match 'home/delivery'               => 'home#delivery',            :as => :home_delivery
  match 'home/grocery'                => 'home#grocery',             :as => :home_grocery
  match 'home/coupons'                => 'home#coupons',             :as => :home_coupons
  match 'home/plans'                  => 'home#plans',               :as => :home_plans

  match 'home/store_overview/:id'     => 'home#store_overview',      :as => :home_store_overview
  match 'home/store_info/:id'         => 'home#store_info',          :as => :home_store_info
  match 'home/store_good/:id'         => 'home#store_good',          :as => :home_store_good
  match 'home/store_menu/:id'         => 'home#store_menu',          :as => :home_store_menu
  match 'home/store_promo/:id'        => 'home#store_promo',         :as => :home_store_promo
  match 'home/store_review/:id'       => 'home#store_review',        :as => :home_store_review
  match 'home/print_coupon/:id'       => 'home#print_coupon',        :as => :home_print_coupon
  match 'home/dish_modal/:id'         => 'home#dish_modal',          :as => :home_dish_modal

  match 'home/paypal_notify'          => 'home#paypal_notify',       :as => :home_paypal_notify
  match 'home/paypal_cancel'          => 'home#paypal_cancel',       :as => :home_paypal_cancel

  match 'home/phone_start'            => 'home#phone_start',         :as => :home_phone_start
  match 'home/phone_end'              => 'home#phone_end',           :as => :home_phone_end
  match 'home/phone_test'             => 'home#phone_test',          :as => :home_phone_test

  resources :advertisements
  resources :carts do
    member do
      get :type
    end
  end
  resources :cart_items
  resources :orders
  resources :payments
  resources :posts
  resources :roles
  resources :services
  resources :tags
  resources :tickets
  resources :transactions

  resources :stores do
    resources :coupons, :dish_choices, :dish_features, :dish_discounts, :hours, :menus, :plans
  end

  resources :menus do
    resources :categories
  end

  resources :categories do
    resources :dishes
  end

  root :to => 'home#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :delivery_type, :delivery_fee, :store, :store_id, :cart_items

  belongs_to :store

  has_many :cart_items, :dependent => :destroy
  has_many :orders

  def add_dish(dish, name, price, quantity, note)
    current_item = cart_items.find_by_cart_itemable_id_and_cart_itemable_type_and_note(dish.id, dish.class.to_s, note)
    if current_item
      current_item.quantity += quantity
    else
      current_item = cart_items.build(cart_itemable: dish, name: name, price: price, quantity: quantity, note: note)
    end
    current_item
  end

  def add_coupon(coupon, name, price, quantity)
    current_item = cart_items.find_by_cart_itemable_id_and_cart_itemable_type(coupon.id, coupon.class.to_s)
    unless current_item
      current_item = cart_items.build(cart_itemable: coupon, name: name, price: price, quantity: quantity)
    end
    current_item
  end

  def update_coupons   # In case the coupon minimum is not reached
    coupon_items = cart_items.where("cart_itemable_type = 'Coupon'")
    coupon_items.each do |ci|
      ci.destroy if ci.cart_itemable.minimum > total_price
    end
    reload # Reload the object of cart_item
  end

  def subtotal_price
    cart_items.to_a.sum { |item| item.total_price }
  end

  def tax
    subtotal_price * 0.0825
  end

  def total_price
    subtotal_price + tax + delivery_fee
  end

  def cash_back
    subtotal_price * store.cash_back_rate
  end

  DELIVERY_TYPES = [['Delivery', 'delivery'], ['Pick Up', 'pick_up']]
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  # Authenticate and load @cart for the whole controller
  load_and_authorize_resource

  # GET /carts
  # GET /carts.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to home_stores_url, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @store = @cart.store
    @cart.destroy

    respond_to do |format|
      format.mjs
      format.js
      format.json { head :no_content }
    end
  end

  # Change cart type: delivery or pick-up
  def type
    @cart.delivery_type = params[:delivery_type]
    @cart.save

    respond_to do |format|
      format.mjs
      format.js
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% if cart.cart_items.empty? %>
    <%= image_tag "/assets/mfm_logo.png" %>
    <h4>Nothing left in your cart!</h4>
<% else %>
    <ul>
      <li><h4 style="margin-top: 0px;">Cart @ <%= cart.store.name %></h4></li>
      <li class="cart_header">
        <% if params[:controller] == "orders" %>
            <% if cart.delivery_type == 'delivery' %>
                <%= link_to 'Delivery', "javascript:;", class: 'active' %>
            <% elsif cart.delivery_type == 'melivery' %>
                <%= link_to 'Delivery.', "javascript:;", class: 'active' %>
            <% elsif cart.delivery_type == 'pick_up' %>
                <%= link_to 'Pick Up', "javascript:;", class: 'active' %>
            <% elsif cart.delivery_type == 'express' %>
                <%= link_to 'Reserve', "javascript:;", class: 'active' %>
            <% end %>
        <% else %>
            <%= link_to 'Delivery', type_cart_path(cart, delivery_type: :delivery), class: (cart.delivery_type == 'delivery') ? 'active' : nil, remote: true if cart.store.has_delivery_service? %>
            <%= link_to 'Delivery.', type_cart_path(cart, delivery_type: :melivery), class: (cart.delivery_type == 'melivery') ? 'active' : nil, remote: true if cart.store.has_melivery_service? %>
            <%= link_to 'Pick Up', type_cart_path(cart, delivery_type: :pick_up), class: (cart.delivery_type == 'pick_up') ? 'active' : nil, remote: true if cart.store.has_pick_up_service? %>
            <%= link_to 'Reserve', type_cart_path(cart, delivery_type: :express), class: (cart.delivery_type == 'express') ? 'active' : nil, remote: true if cart.store.has_express_service? %>
        <% end %>
      </li>

      <%= render(cart.cart_items) %>

      <% unless params[:controller] == "orders" %>
          <li class="cart_coupon">
            <%= form_tag(cart_items_path, method: 'post', remote: true) do %>
                <%= text_field_tag :coupon_id, "", placeholder: 'Coupon Code' %>
                <%= hidden_field_tag :store_id, cart.store.id %>
                <%= submit_tag "Apply", class: "btn btn-info" %>
                <% if @message %>
                    <span style="color: #ff0000;"><%= @message %></span>
                <% end %>
            <% end %>
          </li>
      <% end %>

      <li class="cart_footer">
        <span class="left75">Subtotal:</span>
        <span class="right20"><%= number_to_currency(cart.subtotal_price) %></span>
      </li>
      <li class="cart_footer">
        <span class="left75">Tax:</span>
        <span class="right20"><%= number_to_currency(cart.subtotal_price*0.0825) %></span>
      </li>
      <% if cart.delivery_fee > 0 %>
          <li class="cart_footer">
            <span class="left75">Delivery Fee:</span>
            <span class="right20"><%= number_to_currency(cart.delivery_fee) %></span>
          </li>
      <% end %>
      <li class="cart_footer">
        <span class="left75">Total:</span>
        <span class="right20"><%= number_to_currency(cart.total_price) %></span>
      </li>

      <!--Give cash back when signed in and in a cash_back store-->
      <% if user_signed_in? && cart.store.cash_back_rate > 0 %>
          <li class="cart_footer" style="color:#006400;font-weight:bold;font-family: times;text-align:center;">
            You are earning <%= number_to_currency cart.cash_back %> cash back!
          </li>
      <% end %>

      <!--Be able to edit order if not checkout page-->
      <% unless params[:controller] == "orders" %>
          <li class="cart_footer" style="margin-top: 10px;">
            <% if (cart.delivery_type == "delivery" || cart.delivery_type == "melivery") && (cart.total_price < cart.store.delivery_minimum) %>
                <%= link_to "Min.  #{number_to_currency(cart.store.delivery_minimum)}", 'javascript:;', :class => 'btn pull-right' %>
            <% else %>
                <%= link_to 'Proceed', new_order_path(store_id: cart.store_id), method: :get, :class => 'btn btn-primary pull-right' %>
            <% end %>
            <%= link_to 'Empty cart', cart, :class => 'btn', :remote => true, method: :delete, confirm: 'Are you sure?' %>
          </li>
      <% end %>
    </ul>
<% end %>

app/views/carts/_cart.mobile.erb
<% if cart.cart_items.empty? %>
    <h4>Your Cart Is Empty!</h4>
<% else %>
    <ul data-role="listview">
      <li>
        Cart @ <%= cart.store.name %>
        <div data-role="controlgroup" data-type="horizontal" data-mini="true" class="button-glyphish">
          <% if params[:controller] == "orders" %>
              <% if cart.delivery_type == 'delivery' %>
                  <%= link_to 'Delivery', "javascript:;", data: {role: 'button', theme: 'b'} %>
              <% elsif cart.delivery_type == 'melivery' %>
                  <%= link_to 'Delivery.', "javascript:;", data: {role: 'button', theme: 'b'} %>
              <% elsif cart.delivery_type == 'pick_up' %>
                  <%= link_to 'Pick Up', "javascript:;", data: {role: 'button', theme: 'b'} %>
              <% elsif cart.delivery_type == 'express' %>
                  <%= link_to 'Reserve', "javascript:;", data: {role: 'button', theme: 'b'} %>
              <% end %>
          <% else %>
              <%= link_to 'Delivery', type_cart_path(cart, delivery_type: :delivery), data: {role: 'button',  theme: (cart.delivery_type == 'delivery') ? 'b' : 'a'}, remote: true if cart.store.has_delivery_service? %>
              <%= link_to 'Delivery.', type_cart_path(cart, delivery_type: :melivery), data: {role: 'button', theme: (cart.delivery_type == 'melivery') ? 'b' : 'a'}, remote: true if cart.store.has_melivery_service? %>
              <%= link_to 'Pick Up', type_cart_path(cart, delivery_type: :pick_up), data: {role: 'button', theme: (cart.delivery_type == 'pick_up') ? 'b' : 'a'}, remote: true if cart.store.has_pick_up_service? %>
              <%= link_to 'Reserve', type_cart_path(cart, delivery_type: :express), data: {role: 'button', theme: (cart.delivery_type == 'express') ? 'b' : 'a'}, remote: true if cart.store.has_express_service? %>
          <% end %>
        </div>
      </li>

      <%= render(cart.cart_items) %>

      <li style="text-align: right;font-size: 13px;">
        Subtotal: <%= number_to_currency(cart.subtotal_price) %><br/>
        Tax: <%= number_to_currency(cart.subtotal_price*0.0825) %><br/>
        <% if cart.delivery_fee > 0 %>Delivery Fee: <%= number_to_currency(cart.delivery_fee) %><br/><% end %>
        Total: <%= number_to_currency(cart.total_price) %>

        <!--Give cash back when signed in and in a cash_back store-->
        <% if user_signed_in? && cart.store.cash_back_rate > 0 %>
            <span style="float:left;font-style:italic;">Earning <%= number_to_currency cart.cash_back %> cash back!</span>
        <% end %>
      </li>

      <!--Be able to edit order if not checkout page-->
      <% unless params[:controller] == "orders" %>
          <li>
            <div class="ui-grid-a">
              <div class="ui-block-a">
                <%= link_to "Empty cart", cart, data: {role: "button", mini: true }, remote: true, method: :delete, confirm: "Are you sure?" %>
              </div>
              <div class="ui-block-b">
                <% if cart.delivery_type == "delivery" && cart.total_price < cart.store.delivery_minimum %>
                    <%= link_to "Min. #{number_to_currency(cart.store.delivery_minimum)}", "javascript:;", data: { role: "button", mini: true } %>
                <% else %>
                    <%= link_to "Proceed", new_order_path(store_id: cart.store_id), data: { role: "button", mini: true }, rel: "external" %>
                <% end %>
              </div>
            </div>
          </li>
      <% end %>
    </ul>
<% end %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :delivery_type %><br />
    <%= f.text_field :delivery_type %>
  </div>
  <div class="field">
    <%= f.label :store %><br />
    <%= f.text_field :store %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th>Delivery type</th>
    <th>Store</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= cart.delivery_type %></td>
    <td><%= cart.store.name %></td>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Delivery type:</b>
  <%= @cart.delivery_type %>
</p>

<p>
  <b>Store:</b>
  <%= @cart.store.name %>
</p>


<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>